Models/Gasto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Final_DIARS.Models
{
    public class Gasto
    {
        public int id { get; set; }
        public int id_cuenta { get; set; }
        public string cuenta { get; set; }
        public DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public int monto { get; set; }
    }
}

Models/Ingreso.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Final_DIARS.Models
{
    public class Ingreso
    {
        public int id { get; set; }
        public int id_cuenta { get; set; }
        public string cuenta { get; set; }
        public DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public int monto { get; set; }
    }
}

Controllers/FinanzasController.cs
using Final_DIARS.BDD;
using Final_DIARS.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Examen_Final_DIARS.Controllers
{
    public class FinanzasController : Controller
    {
        private FinanzasContext context;
        
        public FinanzasController(FinanzasContext context)
        {
            this.context = context;
        }

        public List<Cuenta> getCuentas()
        {
            var cu = context.cuentas;
            var id = GetLoggedUser().id;
            var cuenta = cu.Where(r => r.id_user == id).ToList();
            return cuenta;
        }
        public List<Gasto> getGastos(int id)
        {
            var ga = context.gastos;
            var gasto = ga.Where(r => r.id_cuenta == id).ToList();
            return gasto;
        }

        public List<Ingreso> getIngresos(int id)
        {
            var ing = context.ingresos;
            var ingreso = ing.Where(r => r.id_cuenta == id).ToList();
            return ingreso;
        }

        public List<Solicitud> getSolicitudes(int id)
        {
            var sol = context.solicitudes;
            var solic = sol.Where(r => r.id_uDestino == id).ToList();
            return solic;
        }

        public List<Contacto> getContactos(int id)
        {
            var con = context.contactos;
            var contac = con.Where(r => r.id_user == id).ToList();
            return contac;
        }

        public Cuenta buscaCuenta(string nombre)
        {
            var cu = context.cuentas;
            var nom = nombre;
            Cuenta cuenta = cu.First(r => r.nombre == nom);
            return cuenta;
        }
        public Cuenta buscaCuentaUser(string nombre, string destino)
        {
            var cu = context.cuentas;
            var nom = destino;
            var id = getUsuario(nombre).id;
            Cuenta cuenta = cu.First(r => r.nombre == nom && r.id_user==id);
            return cuenta;
        }

        public Usuario getUsuario(string nombre)
        {
            var u = context.usuarios;
            var user = u.First(r => r.nombre == nombre);
            return user;
        }

        public Usuario getUsuarioId(int id)
        {
            var u = context.usuarios;
            var user = u.First(r => r.id == id);
            return user;
        }

        public Solicitud buscaSolicitud(int id)
        {
            var s = context.solicitudes;
            var sol = s.First(r => r.id == id);
            return sol;
        }


        [HttpGet]
        public IActionResult MostrarCuentas()
        {
            var liCuentas = getCuentas();
            return View("MostrarCuentas",liCuentas);
        }
        [HttpGet]
        public IActionResult CrearCuenta()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CrearCuentas(string nombre,string tp,int saldo)
        {
            var id = GetLoggedUser().id;
            Cuenta cu = new Cuenta
            {
                id_user = id,
                nombre = nombre,
                categoria = tp,
                sInicial = saldo
            };
            context.cuentas.Add(cu);
            context.SaveChanges();
            var liCuentas = getCuentas();
            return View("MostrarCuentas",liCuentas);
        }

        [HttpGet]
        public IActionResult AgregarGastos()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AgregarGasto(string nombre, DateTime fecha, string descripcion, int saldo)
        {
            Cuenta cuenta = buscaCuenta(nombre);
            var diferencia = cuenta.sInicial - saldo;
            if (diferencia < 0)
            {
                TempData["AuthMessage"] = "Saldo insuficiente";
                return RedirectToAction("AgregarGastos");
            }
            else
            {
                cuenta.sInicial = cuenta.sInicial - saldo;
                Gasto gasto = new Gasto
                {
                    id_cuenta = cuenta.id,
                    cuenta = nombre,
                    descripcion = descripcion,
                    fecha = fecha,
                    monto = saldo,
                };
                context.cuentas.Update(cuenta);
                context.gastos.Add(gasto);
                context.SaveChanges();
                var liCuentas = getCuentas();
                return RedirectToAction("MostrarCuentas", liCuentas);
            }
        }

        [HttpGet]
        public IActionResult AgregarIngresos()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AgregarIngreso(string nombre, DateTime fecha,string descripcion,int saldo)
        {
            Cuenta cuenta = buscaCuenta(nombre);
            cuenta.sInicial = cuenta.sInicial + saldo;
            Ingreso ingreso = new Ingreso
            {
                id_cuenta = cuenta.id,
                cuenta = nombre,
                descripcion = descripcion,
                fecha = fecha,
                monto = saldo,
            };
            context.cuentas.Update(cuenta);
            context.ingresos.Add(ingreso);
            context.SaveChanges();
            var liCuentas = getCuentas();
            return RedirectToAction("MostrarCuentas", liCuentas);
        }

        [HttpGet]
        public IActionResult Transferencias()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Transferencia(string origen, string destino, DateTime fecha, int saldo)
        {
            Cuenta cor = buscaCuenta(origen);
            Cuenta des = buscaCuenta(destino);
            var diferencia = cor.sInicial - saldo;
            if (diferencia < 0)
            {
                TempData["AuthMessage"] = "Saldo insuficiente";
                return RedirectToAction("Trasferencia");
            }
            else
            {
                cor.sInicial = cor.sInicial - saldo;
                des.sInicial = des.sInicial + saldo;
                Gasto gasto = new Gasto
                {
                    id_cuenta = cor.id,
                    cuenta = origen,
                    descripcion = "Transferencia",
                    fecha = fecha,
                    monto = saldo,
                };
                Ingreso ingreso = new Ingreso
                {
                    id_cuenta = des.id,
                    cuenta = destino,
                    descripcion = "Transferencia",
                    fecha = fecha,
                    monto = saldo,
                };
                context.cuentas.Update(cor);
                context.cuentas.Update(des);
                context.ingresos.Add(ingreso);
                context.gastos.Add(gasto);
                context.SaveChanges();
                var liCuentas = getCuentas();
                return RedirectToAction("MostrarCuentas", liCuentas);
            }
        }

        [HttpGet]
        public IActionResult Gastos(int id)
        {
            var liGastos = getGastos(id);
            return View("Gastos", liGastos);
        }
        [HttpGet]
        public IActionResult Ingresos(int id)
        {
            var liIngresos = getIngresos(id);
            return View("Ingresos", liIngresos);
        }
        [HttpGet]
        public IActionResult EnviarSolicitudes()
        {
            return View();
        }
        [HttpPost]
        public IActionResult EnviarSolicitud(string nombre)
        {
            var id = GetLoggedUser().id;
            var user = getUsuario(nombre).id;
            var nom = GetLoggedUser().nombre;
            Solicitud solicitud = new Solicitud
            {
                id_uOrigen = id,
                id_uDestino = user,
                nombre = nom
            };
            context.solicitudes.Add(solicitud);
            context.SaveChanges();
            var liCuentas = getCuentas();
            return View("MostrarCuentas", liCuentas);
        }

        [HttpGet]
        public IActionResult MostrarSolicitudes()
        {
            var id = GetLoggedUser().id;
            var liSolicitud = getSolicitudes(id);
            return View("MostrarSolicitudes",liSolicitud);
        }

        public IActionResult AceptarSolicitud(int id)
        {
            var id_user = GetLoggedUser().id;
            var nom = buscaSolicitud(id).nombre;
            var sol = buscaSolicitud(id);
            Contacto contacto = new Contacto
            {
                id_user = id_user,
                nombre = nom
            };
            context.contactos.Add(contacto);
            context.solicitudes.Remove(sol);
            context.SaveChanges();
            var liCuentas = getCuentas();
            return View("MostrarCuentas", liCuentas);
        }

        [HttpGet]
        public IActionResult MostrarContactos()
        {
            var id = GetLoggedUser().id;
            var liContacto = getContactos(id);
            return View("MostrarContactos",liContacto);
        }

        [HttpGet]
        public IActionResult TransferenciaUsuario()
        {
            return View();
        }

        [HttpPost]
        public IActionResult TransferenciaUsuarios(string origen, string nombre, string destino, DateTime fecha, int saldo)
        {
            Cuenta cor = buscaCuenta(origen);
            Cuenta des = buscaCuentaUser(nombre,destino);
            var diferencia = cor.sInicial - saldo;
            if (diferencia < 0)
            {
                TempData["AuthMessage"] = "Saldo insuficiente";
                return RedirectToAction("Trasferencia");
            }
            else
            {
                cor.sInicial = cor.sInicial - saldo;
                des.sInicial = des.sInicial + saldo;
                Gasto gasto = new Gasto
                {
                    id_cuenta = cor.id,
                    cuenta = origen,

Views/Finanzas/AgregarGastos.cshtml
<head>
    <title>Nuevo gasto</title>
</head>

<body>
    <h1>Registra tus gastos</h1>
    <form action="~/Finanzas/AgregarGasto" method="post">
        <p>Cuenta</p>
        <input class="input" type="text" name="nombre" placeholder="Nombra tu cuenta" required />
        <p>Fecha</p>
        <input type="date" name="fecha" required />
        <p>Descripcion</p>
        <input class="input" type="text" name="descripcion" required />
        <p>Monto</p>
        <input class="input" type="text" name="saldo" required /><br />
        <button id="insesion" class="button is-link">Agregar</button>
        <a href="/#" class="button is-link is-light" style="top: 20px; position: relative;">Cancelar</a>
    </form>
</body>

Views/Finanzas/AgregarIngresos.cshtml
<head>
    <title>Nuevo ingreso</title>
</head>

<body>
    <h1>Registra tus ingresos</h1>
    <form action="~/Finanzas/AgregarIngreso" method="post">
        <p>Cuenta</p>
        <input class="input" type="text" name="nombre" placeholder="Nombra tu cuenta" required />
        <p>Fecha</p>
        <input type="date" name="fecha" required />
        <p>Descripcion</p>
        <input class="input" type="text" name="descripcion" required />
        <p>Monto</p>
        <input class="input" type="text" name="saldo" required /><br />
        <button id="insesion" class="button is-link">Agregar</button>
        <a href="/#" class="button is-link is-light" style="top: 20px; position: relative;">Cancelar</a>
    </form>
</body>

Views/Finanzas/CrearCuenta.cshtml
<head>
    <title>Nueva Cuenta</title>
</head>

<body>
    <div>
        <div>
            <form action="~/Finanzas/CrearCuentas" method="post">
                <p>Nombre</p>
                <input class="input" type="text" name="nombre" placeholder="Nombra tu cuenta" required />
                <p>Categoria</p>
                <div class="opciones-init">
                    <select name="tp">
                        <option value="Propio">Propio</option>
                        <option value="Credito">Credito</option>
                    </select>
                </div>
                <p>Saldo</p>
                <input class="input" type="text" name="saldo" required /><br />
                <button id="insesion" class="button is-link">Crear</button>
                <a href="/#" class="button is-link is-light" style="top: 20px; position: relative;">Cancelar</a>
            </form>
        </div>
    </div>
</body>

Views/Finanzas/EnviarSolicitudes.cshtml
<head>
    <title>Enviar solicitud</title>
</head>

<body>
    <h1>Aqui envio solicitudes</h1>
    <form action="~/Finanzas/EnviarSolicitud" method="post">
        <p>Nombre</p>
        <input class="input" type="text" name="nombre" placeholder="Nombra tu cuenta" required />
        <button id="insesion" class="button is-link">Enviar</button>
        <a href="/#" class="button is-link is-light" style="top: 20px; position: relative;">Cancelar</a>
    </form>
</body>

Views/Finanzas/Gastos.cshtml
<head>
    <title>Mis gasto</title>
</head>

<body>
    <h1>Mis cuentas</h1><br />
    <div>
        <div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Cuenta</th>
                        <th>Fecha</th>
                        <th>Descripcion</th>
                        <th>Monto</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Gasto cu in Model)
                     {
                        <tr>
                            <td>@cu.cuenta</td>
                            <td>@cu.fecha</td>
                            <td>@cu.descripcion</td>
                            <td>@cu.monto</td>
                        </tr>
                     }
                </tbody>
            </table>
        </div>
    </div>
</body>

Views/Finanzas/Ingresos.cshtml
<head>
    <title>Mis ingresos</title>
</head>

<body>
    <h1>Mis cuentas</h1><br />
    <div>
        <div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Cuenta</th>
                        <th>Fecha</th>
                        <th>Descripcion</th>
                        <th>Monto</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Ingreso cu in Model)
                     {
                        <tr>
                            <td>@cu.cuenta</td>
                            <td>@cu.fecha</td>
                            <td>@cu.descripcion</td>
                            <td>@cu.monto</td>
                        </tr>
                     }
                </tbody>
            </table>
        </div>
    </div>
</body>

Views/Finanzas/MostrarContactos.cshtml
<head>
    <title>Mis contactos</title>
</head>

<body>
    <h1>Mis contactos</h1><br />
    <div>
        <div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Nombre</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Contacto cu in Model)
                    {
                        <tr>
                            <td>@cu.nombre</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>

Views/Finanzas/MostrarCuentas.cshtml
<head>
    <title>Cuentas</title>
</head>

<body>
    <h1>Mis cuentas</h1><br />
    <div>
        <div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Categoria</th>
                        <th>Saldo</th>
                        <th>Ingresos</th>
                        <th>Gastos</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Cuenta cu in Model)
                    {
                    <tr>
                        <td>@cu.nombre</td>
                        <td>@cu.categoria</td>
                        <td>@cu.sInicial</td>
                        <td><a class="btn-info nav-link text-dark text-center" href="~/Finanzas/Ingresos?id=@cu.id">Ingresos</a></td>
                        <td><a class="btn-warning nav-link text-dark text-center" href="~/Finanzas/Gastos?id=@cu.id">Gastos</a></td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div>
        <a class="nav-link text-dark" asp-controller="Finanzas" asp-action="CrearCuenta"><h5>Crear cuenta nueva</h5></a>
        <a class="nav-link text-dark" asp-controller="Finanzas" asp-action="AgregarIngresos"><h5>Agregar ingresos</h5></a>
        <a class="nav-link text-dark" asp-controller="Finanzas" asp-action="AgregarGastos"><h5>Agregar gastos</h5></a>
        <a class="nav-link text-dark" asp-controller="Finanzas" asp-action="Transferencias"><h5>Hacer una transferencia</h5></a>
    </div>
    <div>
        <a class="nav-link text-dark" asp-controller="Finanzas" asp-action="MostrarContactos"><h5>Mis contactos</h5></a>
        <a class="nav-link text-dark" asp-controller="Finanzas" asp-action="EnviarSolicitudes"><h5>Enviar solicitudes</h5></a>
        <a class="nav-link text-dark" asp-controller="Finanzas" asp-action="MostrarSolicitudes"><h5>Ver solicitudes</h5></a>
        <a class="nav-link text-dark" asp-controller="Finanzas" asp-action="TransferenciaUsuario"><h5>Trasferencia a un amigo</h5></a>
    </div>
</body>

Views/Finanzas/MostrarSolicitudes.cshtml
<head>
    <title>Mis solicitudes</title>
</head>

<body>
    <h1>Mis solicitudes</h1><br />
    <div>
        <div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Aceptar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Solicitud cu in Model)
                    {
                        <tr>
                            <td>@cu.nombre</td>
                            <td><a class="btn-info nav-link text-dark text-center" href="~/Finanzas/AceptarSolicitud?id=@cu.id">Aceptar</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>

Views/Finanzas/TransferenciaUsuario.cshtml
<head>
    <title>Transferencias entre usuarios</title>
</head>

<body>
    <h1>Transfiere a tus amigos</h1>
    <div>
        <div>
            <form action="~/Finanzas/TransferenciaUsuarios" method="post">
                <p>Cuenta de origen</p>
                <input class="input" type="text" name="origen" placeholder="Nombra tu cuenta" required />
                <p>Nombre de tu amigo</p>
                <input class="input" type="text" name="nombre" placeholder="Nombra a tu amigo" required />
                <p>Cuenta de destino</p>
                <input class="input" type="text" name="destino" placeholder="Nombra la cuenta de tu amigo" required />
                <p>Fecha</p>
                <input type="date" name="fecha" required />
                <p>Monto</p>
                <input class="input" type="text" name="saldo" required /><br />
                <button id="insesion" class="button is-link">Realizar transferencia</button>
                <a href="/#" class="button is-link is-light" style="top: 20px; position: relative;">Cancelar</a>
            </form>
        </div>
    </div>
</body>

Views/Finanzas/Transferencias.cshtml
<head>
    <title>Tranferencias</title>
</head>

<body>
    <h1>Realiza una transferencia</h1>
    <div>
        <div>
            <form action="~/Finanzas/Transferencia" method="post">
                <p>Cuenta de origen</p>
                <input class="input" type="text" name="origen" placeholder="Nombra tu cuenta" required />
                <p>Cuenta de destina</p>
                <input class="input" type="text" name="destino" placeholder="Nombra tu cuenta" required />
                <p>Fecha</p>
                <input type="date" name="fecha" required />
                <p>Monto</p>
                <input class="input" type="text" name="saldo" required /><br />
                <button id="insesion" class="button is-link">Realizar transferencia</button>
                <a href="/#" class="button is-link is-light" style="top: 20px; position: relative;">Cancelar</a>
            </form>
        </div>
    </div>
</body>